from nmcli_gui_application import MainWindow

APP_NAME = "Wireless Connection"

APPLICATION_START_X_COORDINATE = 30
APPLICATION_START_Y_COORDINATE = 600

APPLICATION_X_SIZE = 220
APPLICATION_Y_SIZE = 300

if __name__ == '__main__':
	MainWindow(
		APP_NAME,
		APPLICATION_START_X_COORDINATE,
		APPLICATION_START_Y_COORDINATE,
		APPLICATION_X_SIZE,
		APPLICATION_Y_SIZE
		)